### ISSUE TITLE
⬆️ Upgrade gitmojis to v3.5.0

### ISSUE THREAD

**Issue by johannchopin** [johannchopin/gitmoji-browser-extension#115]
Hello Team 👋

**Describe the feature that you want see**
Upgrade and bumps gitmojis package version to v3.5.0.

TODO:

- [x] Upgrade package
- [x] Add missing color for the new 👔(`:necktie:`) gitmojis
- [x] Fix tests

**Comment by johannchopin** [comment]
@Lyokolux ?

**Comment by Lyokolux** [comment]
Done ✅
