### ISSUE TITLE
🐛 Dependabot can't find "⬆️ dependencies" label

### ISSUE THREAD

**Issue by sercanuste** [johannchopin/gitmoji-browser-extension#176]
Hello Team 👋

**Describe the bug**
Dependabot can't find `⬆️ dependencies` label. '⬆️ ' part missing on 'dependencies' label. Updating label can fix this.

**Device (please complete the following information):**
Dependabot comment > https://github.com/johannchopin/gitmoji-browser-extension/pull/174#issuecomment-1264359554

![image](https://user-images.githubusercontent.com/5119317/193471357-68a1e495-9e15-4900-9bec-e5910dd67927.png)

**Comment by johannchopin** [comment]
Hey @sercanuste 👋  Thanks for the help 👍 

Dependabot has been neglected for a while but I intend to put this flow back in place.
The label has been updated ✅
