### ISSUE TITLE
Publish the extension on Edge Addons too

### ISSUE THREAD

**Issue by max-programming** [johannchopin/gitmoji-browser-extension#37]
Hello Team 👋

I really like Gitmoji and I love using it. It's very helpful for me. Just a quick suggestion about publishing the extension to the [Microsoft Edge Add-ons](https://microsoftedge.microsoft.com/addons/) also. And as Edge is now based on Chromium, the extension code will be the same as Chrome. I know I can install and use it from the Chrome web store but it is good to be cross platform. People might search on Edge addons and they might not see gitmoji

**Comment by johannchopin** [comment]
Hey @max-programming 👋

Thanks for the proposition it makes totally sense to have it on this store 👍 I will have a look.

**Comment by max-programming** [comment]
> Hey @max-programming 👋
> 
> Thanks for the proposition it makes totally sense to have it on this store 👍 I will have a look. 

Thanks for your kind reply

**Comment by johannchopin** [comment]
The extension is now on this store too 👍 Thanks again for the idea and the time you invested by opening this issue 🎉  Feel also free to rate this extension if you want to support it a little further 😉

**Comment by max-programming** [comment]
> The extension is now on this store too 👍 Thanks again for the idea and the time you invested by opening this issue 🎉 Feel also free to rate this extension if you want to support it a little further 😉

Thanks! Yeah I'll rate the extension for sure
