### ISSUE TITLE
🐛 Link to french Firefox add-on page

### ISSUE THREAD

**Issue by Daybringer** [johannchopin/gitmoji-browser-extension#41]
Great repo, my first issue on GH so sorry for bad form, etc.

**Describe the bug**
The link on readme to the Firefox add-on page leads to the french version. 
English language (https://addons.mozilla.org/en-US/firefox/addon/gitmoji-browser-extension/) might be more suitable.

**Device (please complete the following information):**
 - OS: [Linux]
 - Browser [Firefox Dev. Edition]

**Comment by johannchopin** [comment]
Hey @Daybringer 👋 Ouupsi yes this is definitely something to fix thanks for reporting us this issue 👍 

Have a good one in the OS world 😉

**Comment by johannchopin** [comment]
Fixed in #42 👍
