### ISSUE TITLE
✨ Show description when hovering over gitmoji

### ISSUE THREAD

**Issue by mirror-kt** [johannchopin/gitmoji-browser-extension#55]
Hello Team 👋

**Describe the feature that you want see**
I want the description on gitmoji.dev to be shown as an overlay when hovering over gitmoji in list.
## Example
When hovering the emoji `:art:`, the description `Improve structure / format of the code.` is shown.

**Comment by johannchopin** [comment]
Hey @mirror-kt 👋 

This would be really a nice and helpful improvement to the extension. Do you planned to take care of it? If you don't have the time I could spent some time on it 👍 

I guess we could just make the description appear bellow the gitmoji's row on `hover` but also on `focus` since the extension should also be used with the tab key.

**Comment by mirror-kt** [comment]
If I could write svellte, I did it myself, but I can't write much😭.

So, could you take care of it?

P.S. focus a good idea!
I'm looking forward to future development!

**Comment by johannchopin** [comment]
I implemented it in #61 so feel free to checkout this branch and see the result by running `yarn start` or `npm run start` and give a feedback 👍

**Comment by mirror-kt** [comment]
![スクリーンショット 2021-02-02 20 57 26](https://user-images.githubusercontent.com/43880251/106597116-4d869780-6599-11eb-9ad6-d4b7324c0ca5.png)
It seems that the description of the bottom line is displayed outside the frame 👀.

**Comment by johannchopin** [comment]
Yes true but IMHO it doesn't worth the effort to implement this feature. Most of this extension users already now which gitmoji they want and use the search input. So in mosts cases the needed gitmoji is not at the end of the list. If it is you can then use your arrow-down key or scroll a little. In know it's not the best user-friendly implementation but it's a good start. Is it ok then to just leave it like it is? 👍

**Comment by mirror-kt** [comment]
I see, that's OK!
LGTM, thanks😄
