### ISSUE TITLE
✨ Help user open PRs

### ISSUE THREAD

**Issue by vhoyer** [johannchopin/gitmoji-browser-extension#7]
Hello Team 👋

**Describe the feature that you want see**
You know when you open a new PR, and there is only one commit, so Github put's the commit message in the title of the PR?

Then if I inserted :card_file_box:, for example. in the title of the PR I see:

![image](https://user-images.githubusercontent.com/11022464/87182377-6ad0dd00-c2ba-11ea-8354-3fd93a20dabb.png)

It would be super great if there was something to help me find the right emoji for this situation:

I image 2 possible solutions:

1. Having a first section on the popup called `suggestion`, and it scans the current page for mentioned emojis
2. The extension adds an option on the `contextmenu` of the page for converting the string(`:shortcode:` to unicode, or vice-versa).

**Comment by johannchopin** [comment]
Hey @vhoyer 👋 

The initial idea of the extension was to implement your second idea 😄 But after reflection that seems to need a lot of work since there was a lot of case to cover (Ex: what if you want in some case see the shortcode instead of the emoji). 

Really love your first idea 👍 The question is how to implement it in such a small interface so as not to 'pollute' the interface for users who don't want to use this feature.

**Comment by vhoyer** [comment]
maybe we can add a settings page? I've seen other extensions with settings pages 😊

**Comment by vhoyer** [comment]
actually, we could just sort the emojis on the list, and if the user types anything, we sort normally.

Is there still a reason to not want this feature?

**Comment by johannchopin** [comment]
Another question is if you see that your gitmoji is shown as `:card_file_box_`, why not use the extension and just start typing `card...` and select the gitmoji? 🤔

**Comment by vhoyer** [comment]
well, that's what I've been doing so far, but I found prefer if I did not need to type anything,


like, I already had to take my hands of the keyboard to click on the extension, I do not want to have to get my hand back at the keyboard just to take it of again to click on the emoji, that would be two unoptimized movements 😅

**Comment by johannchopin** [comment]
Well I see the point if you use the mouse. But this extension was build so you don't need  to use your mouse 👍 

You can just open it using the shortcut <kbd>Alt+G</kbd> (<kbd>⌥+G</kbd> for mac). The input is in autofocus so you can directly write something and then just use <kbd>Tab</kbd> to navigate to the gitmoji and finally press <kbd>Enter</kbd>.

Use it like this allow you to never take your hands form your keyboard and make your research amazingly fast (in most case I get my gitmoji with 3 letters and just hit <kbd>Tab</kbd> once).

**Comment by vhoyer** [comment]
UUU, this is nice news, didn't knew about the shortcuts, nicely done.

Still, I think it's a nice feature to have for our fellow mouse power users :smiley:

**Comment by johannchopin** [comment]
Yep your are right. I think thats cool to see on the top of the list the gitmoji present in the page (shortcode or emoji). And if you start typing just keep the usual behaviour like you propose 👍 

What do you think of having a little eye icon to 'signal' to the user that the gitmoji is present on the page?

**Comment by vhoyer** [comment]
> What do you think of having a little eye icon to 'signal' to the user that the gitmoji is present on the page?

Seems like a cool idea, apparently, there is a lot of space on the right side of the item :D

**Comment by johannchopin** [comment]
That true but I was also thinking about adding a chevron icon to collapse the description of the gitmoji after the proposition of [@KaKi87](https://github.com/KaKi87). But it will still stay some space 😄

**Comment by johannchopin** [comment]
Fix by #10
