### ISSUE TITLE
✨ Automatically add 🔀 in front of merge commit title input in GitHub/GitLab

### ISSUE THREAD

**Issue by johannchopin** [johannchopin/gitmoji-browser-extension#73]
Hello Team 👋

**Describe the feature that you want see**

In a PR, GitHub can automatically merge your branch with a generated message:
![image](https://user-images.githubusercontent.com/31794680/115364185-6c252380-a1c3-11eb-9c53-ab2ab7861e79.png)

I could be really useful that the extension detect it and add the 🔀 or `:twisted_rightwards_arrows:` gitmoji in front of the message.

**Comment by Lyokolux** [comment]
Does the same goes for Gitlab :thinking: ?
