### ISSUE TITLE
Why does Firefox Add-On requires GitHub/GitLab permissions?

### ISSUE THREAD

**Issue by connorjs** [johannchopin/gitmoji-browser-extension#75]
Hello Team 👋🏻

I received a notification today that the latest version of the [Firefox Extension](https://addons.mozilla.org/en-US/firefox/addon/gitmoji-browser-extension/) requires GitHub and GitLab permissions.

> This add-on needs to:
>
> Access your data for github.com
> Access your data for gitlab.com

Why does the browser add-on need this data?

_For now, I have ignored this latest update and not granted permissions. Also, I did not check Chrome or Edge (I only use it with Firefox)._

**Comment by connorjs** [comment]
Does this relate to #73 in anyway? I see its title mentioned GitHub and GitLab and that #74, which resolved it, merged earlier today.

**Comment by johannchopin** [comment]
Hey @connorjs 👋 

Yes this permission are needed to make the feature #73 work. We restricted this permission to the minimum by using really [specific URLs](https://github.com/johannchopin/gitmoji-browser-extension/blob/master/manifest.json#L29):
- `https://github.com/*/*/pull/*`
- `https://gitlab.com/*/*/-/merge_requests/*`

And the script that is executed can be checked [here](https://github.com/johannchopin/gitmoji-browser-extension/blob/master/src/injectMergeGitmoji.js).

**Comment by Lyokolux** [comment]
> Why does the browser add-on need this data?

Ok I need to specify this on the description of the addons for sure :+1:

**Comment by connorjs** [comment]
I really like the targets put forth in #77! Feel free to close at y'all's leisure.

And thanks for the information.
