### ISSUE TITLE
📝 Add section in README about the credentials needed

### ISSUE THREAD

**Issue by johannchopin** [johannchopin/gitmoji-browser-extension#76]

**Comment by Lyokolux** [comment]
Needed or a description of what is available ?

As far as I see, there are 3 options:
* Dark mode
* Close extension after copying a gitmoji
* Show description on hover or focus

The extensions works without configuration, but highlighting them will be useful :+1:

**Comment by Lyokolux** [comment]
Wrap it in to #77

**Comment by johannchopin** [comment]
So lets close this one 👍
