### ISSUE TITLE
📝 Updating the description in the browser stores and README

### ISSUE THREAD

**Issue by Lyokolux** [johannchopin/gitmoji-browser-extension#77]
Hello Team 👋

I think the extension changed enough since the first publication. The descriptions on the stores and in the README should be updated, including:
* [x] a description of the required permissions: what are they used for ?  (related to #75)
* [x] a part about the config available. At the 2021-04-23, these features are configurable:
  * the Dark mode
  * close the extension on a gitmoji copy
  * show the description of a gitmoji on hover or focus
* [x] how to use the extension with the shortcuts
* [x] README updated
* [ ] Descriptions in the stores updated (#79)
  * [ ] Chrome → html format is not possible, redirect to the README instead
  * [x] Firefox

**Comment by Lyokolux** [comment]
Task "Descriptions in the stores updated" not done yet.

**Comment by johannchopin** [comment]
Chrome store doesn't support html description so I will just leave the actual one 👍
